git:
  submodules: false
language: scala
sudo: false

cache:
  directories:
    $INSTALL_DIR

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PDK_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin
    CHISEL3=3.3-SNAPSHOT
    CHISEL_TESTERS=1.4-SNAPSHOT

before_install:
    sudo apt-get install gperf

install:
  #- bash .install_verilator.sh
  #- bash .install_iverilog.sh
  #- bash .install_yosys.sh
  - bash .setup_pdk.sh
  - bash .setup_openlane.sh

script:
  #- set -o pipefail && sbt -Dchisel3Version=$CHISEL3 -Dchisel-iotestersVersion=$CHISEL_TESTERS test
  # Setup docker container 
  docker run -it -v $(pwd):/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -e PDK_ROOT=$PDK_ROOT -u $(id -u $USER):$(id -g $USER) openlane:rc2
  # Run flow for design SPM as test
  ./flow.tcl -design spm
